In [1]:
import json
import openai

In [54]:
openai.api_key ='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'

In [90]:
prediction_dir='/home/donaldo9603/workspace/numeric/data/nq/500samples/r2d2/8512_nq_num_500_r2d2.json'

In [91]:
with open(prediction_dir) as f:
    pred=json.load(f)

### R2D2

In [130]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.954
0.908

### LLAMA zero

In [127]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.656
0.846

### LLAMA-few

In [133]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.908
0.89

In [134]:
for d in pred:
    if d['insteval']!=d['insteval_few']:
        print(d['question'])
        print(d['prediction'])
        print(d['answer'])
        print(d['insteval'])
        print(d['insteval_few'])
        print(d['human'])

when does rick and morty play on tv
 Adult Swim
['late-night']
1
0
0
when is the opening ceremonies of the olympics 2018
 February 9th
['9 February 2018']
0
1
1
when was the cleveland browns last winning game
 December 24, 2016
['2016']
1
0
1
what is the share of agriculture in indian economy
 17%
['17.32%', '23%']
1
0
1
when did i'm like a bird come out
 2000
['October 24, 2000']
1
0
1
how old is baby in dirty dancing movie
 Frances “Baby” Houseman
['17-year-old', '17']
1
0
0
when did marathon change its name to snickers
 1990
['19 July 1990']
1
0
1
when was the last time new zealand had an earthquake
 2016 Kaikoura earthquake
['11 Jul 2017']
1
0
0
when do the walking dead comics come out
 Every 4-6 weeks
['October 2003 - present', '2003']
1
0
0
when do they put the rockefeller tree up
 early November
['mid November', 'late November or early December']
0
1
0
when was the last time ny rangers won stanley cup
 1994
['1993-94']
1
0
1
who does the democratic republic of congo trade with
 China
['Group of 77', 'WTO', 'Zimbabwe', 'Belgium', 'SADC', 'Kenya', 'South Africa', 'China', 'AU', 'Zambia', 'IMF', 'World Bank', 'African Development Bank', 'France']
1
0
1
when does the new season of are you the one come on
 January 10th
['2018']
1
0
0
when does star trek discovery air on tv
 Sunday nights on CBS All Access
['September 19, 2017']
1
0
0
when did a wrinkle in time start filming
 November 2016
['November 2, 2016']
1
0
1
when was the first nuclear power plant opened
 Obninsk, Russia
['December 20, 1951', 'June 27, 1954', 'On June 27, 1954', 'the USSR', 'December 2, 1942']
1
0
0
what channel is abc on in phoenix arizona
 KNXV-TV
['15']
1
0
0
when does the new death of superman come out
 March 28, 2018
['2019', '2018', 'in 2018 and 2019', 'late 2018']
1
0
1
when did canada sign the un declaration of indigenous rights
 2010
['May 2016', '12 November 2010']
1
0
1
love is not love that alters when it alteration finds meaning
 William Shakespeare
['Sonnet 116']
1
0
0
when was the last time giants won superbowl
 Super Bowl XLVI (46)
['2011']
1
0
0
when does the second half of vikings season 5 air
 November 28, 2018
['2018', 'in 2018']
1
0
1
when did the crucifix become the symbol of christianity
 431 CE
['in the 2nd century', '4th century', 'the 4th century']
1
0
0
when was the minimum wage established in the united states
 September 1, 1939
['1938', '1933', '1912']
1
0
0
when did jack mccoy join law and order
 Season 10
['1994']
1
0
0
why did ric flair go back to wcw
 He was offered a contract by WCW that was more lucrative than the one he had with the WWF.
['February 1993']
1
0
0
when did lionel messi play his first game for barcelona
 October 16, 2004
['2002', '2001', 'October 2004']
1
0
1
when was the last god of war made
 2018
['2018', 'March 12, 2013']
1
0
1
what do mobile numbers start with in the uk
 07
['0']
0
1
1
when did the first fleet arive in australia
 January 26, 1788
['18 January 1788', '1788']
1
0
1
how many languages in harry potter translated into
 over 80 languages
['over 74', 'over 74 languages']
0
1
1
when were the winnie the pooh books written
 1924
['1924', '1926', '1927', '1928']
1
0
1
the probability of making a type i error when retaining ho at the .05 level of significance is
.05
['5%']
1
0
1
when was the design period known as art deco
 1920s to 1940s
['1910–1939']
0
1
0
what is the weight of a honda fit
 2,512 to 2,646 pounds
['1,020–1,080\xa0kg']
0
1
0
when does the heart develop and begin pumping blood
 5 weeks after fertilization
['by week 4 of development', 'week 4 of development']
0
1
0
when did drop it like it's hot release
 2004
['September 12, 2004']
1
0
1
when was the last time the carolina hurricanes made the playoffs
 2009
['2008–09']
1
0
1
when did david akers kick the 63 yard field goal
 2012
['September 9, 2012']
1
0
1
what is the average height of a chinese man
 171.2 cm
['5\xa0ft 6\xa0in']
0
1
0
when did beryl markham fly across the atlantic
 1936
['September 1936', '4 September 1936']
0
1
1
who wrote antigone and what are the dates of his birth and death
 Sophocles
['winter 406/5 BC', 'c. 497/6', 'Sophocles']
1
0
1
when did the movie varsity blues come out
 1999
['1999', 'January\xa015,\xa01999']
1
0
1
when did gimme gimme gimme start
 1999
['8 January 1999', '1999']
1
0
1
when did they stop making pull tabs on beer cans
 1980s
['1990', '1970s']
1
0
0
when did the book thief movie come out
 2013
['November 27, 2013', '2013', 'November\xa027,\xa02013']
1
0
1
what episode does marnie come back in geordie shore
 Season 14, Episode 5
['5']
1
0
1
when is the strictly come dancing results show recorded
 Sunday
['Saturday', 'Sunday night']
1
0
1
when was the r10+20 summit in rio de janeiro held
 2012
['June 2012', '13 to 22 June 2012']
1
0
1
how long is the famous suspension bridge in san francisco and what is it called
 Golden Gate Bridge
['one-mile-wide', 'Golden Gate Bridge']
1
0
1
last episode of what happens to my family
 “Father’s Love”
['53']
1
0
0
when does body temperature tend to be lowest
 during sleep
['11 p.m. to 3 a.m.']
1
0
1
when does zay come to girl meets world
 Season 3
['May\xa013,\xa02015']
1
0
0
when does the sword art online movie take place
 between the events of the second and third seasons
['2026', 'the year 2026']
1
0
0
when did come fly with me come out
 2010
['25 December 2010']
1
0
1
when are the next commonwealth games going to be held
 Gold Coast, Australia
['2022']
1
0
0
when did the broncos win the super bowl
 1997, 1998, and 2013
['1998', '2015', '1997']
0
1
1

### Inst-zero

In [115]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.662
0.88

### Inst-few

In [159]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.908
0.89

In [160]:
for d in pred:
    if d['insteval']!=d['insteval_few']:
        print(d['question'])
        print(d['prediction'])
        print(d['answer'])
        print(d['insteval'])
        print(d['insteval_few'])
        print(d['human'])

when does rick and morty play on tv
 Adult Swim
['late-night']
1
0
0
when is the opening ceremonies of the olympics 2018
 February 9th
['9 February 2018']
0
1
1
when was the cleveland browns last winning game
 December 24, 2016
['2016']
1
0
1
what is the share of agriculture in indian economy
 17%
['17.32%', '23%']
1
0
1
when did i'm like a bird come out
 2000
['October 24, 2000']
1
0
1
how old is baby in dirty dancing movie
 Frances “Baby” Houseman
['17-year-old', '17']
1
0
0
when did marathon change its name to snickers
 1990
['19 July 1990']
1
0
1
when was the last time new zealand had an earthquake
 2016 Kaikoura earthquake
['11 Jul 2017']
1
0
0
when do the walking dead comics come out
 Every 4-6 weeks
['October 2003 - present', '2003']
1
0
0
when do they put the rockefeller tree up
 early November
['mid November', 'late November or early December']
0
1
0
when was the last time ny rangers won stanley cup
 1994
['1993-94']
1
0
1
who does the democratic republic of congo trade with
 China
['Group of 77', 'WTO', 'Zimbabwe', 'Belgium', 'SADC', 'Kenya', 'South Africa', 'China', 'AU', 'Zambia', 'IMF', 'World Bank', 'African Development Bank', 'France']
1
0
1
when does the new season of are you the one come on
 January 10th
['2018']
1
0
0
when does star trek discovery air on tv
 Sunday nights on CBS All Access
['September 19, 2017']
1
0
0
when did a wrinkle in time start filming
 November 2016
['November 2, 2016']
1
0
1
when was the first nuclear power plant opened
 Obninsk, Russia
['December 20, 1951', 'June 27, 1954', 'On June 27, 1954', 'the USSR', 'December 2, 1942']
1
0
0
what channel is abc on in phoenix arizona
 KNXV-TV
['15']
1
0
0
when does the new death of superman come out
 March 28, 2018
['2019', '2018', 'in 2018 and 2019', 'late 2018']
1
0
1
when did canada sign the un declaration of indigenous rights
 2010
['May 2016', '12 November 2010']
1
0
1
love is not love that alters when it alteration finds meaning
 William Shakespeare
['Sonnet 116']
1
0
0
when was the last time giants won superbowl
 Super Bowl XLVI (46)
['2011']
1
0
0
when does the second half of vikings season 5 air
 November 28, 2018
['2018', 'in 2018']
1
0
1
when did the crucifix become the symbol of christianity
 431 CE
['in the 2nd century', '4th century', 'the 4th century']
1
0
0
when was the minimum wage established in the united states
 September 1, 1939
['1938', '1933', '1912']
1
0
0
when did jack mccoy join law and order
 Season 10
['1994']
1
0
0
why did ric flair go back to wcw
 He was offered a contract by WCW that was more lucrative than the one he had with the WWF.
['February 1993']
1
0
0
when did lionel messi play his first game for barcelona
 October 16, 2004
['2002', '2001', 'October 2004']
1
0
1
when was the last god of war made
 2018
['2018', 'March 12, 2013']
1
0
1
what do mobile numbers start with in the uk
 07
['0']
0
1
1
when did the first fleet arive in australia
 January 26, 1788
['18 January 1788', '1788']
1
0
1
how many languages in harry potter translated into
 over 80 languages
['over 74', 'over 74 languages']
0
1
1
when were the winnie the pooh books written
 1924
['1924', '1926', '1927', '1928']
1
0
1
the probability of making a type i error when retaining ho at the .05 level of significance is
.05
['5%']
1
0
1
when was the design period known as art deco
 1920s to 1940s
['1910–1939']
0
1
0
what is the weight of a honda fit
 2,512 to 2,646 pounds
['1,020–1,080\xa0kg']
0
1
0
when does the heart develop and begin pumping blood
 5 weeks after fertilization
['by week 4 of development', 'week 4 of development']
0
1
0
when did drop it like it's hot release
 2004
['September 12, 2004']
1
0
1
when was the last time the carolina hurricanes made the playoffs
 2009
['2008–09']
1
0
1
when did david akers kick the 63 yard field goal
 2012
['September 9, 2012']
1
0
1
what is the average height of a chinese man
 171.2 cm
['5\xa0ft 6\xa0in']
0
1
0
when did beryl markham fly across the atlantic
 1936
['September 1936', '4 September 1936']
0
1
1
who wrote antigone and what are the dates of his birth and death
 Sophocles
['winter 406/5 BC', 'c. 497/6', 'Sophocles']
1
0
1
when did the movie varsity blues come out
 1999
['1999', 'January\xa015,\xa01999']
1
0
1
when did gimme gimme gimme start
 1999
['8 January 1999', '1999']
1
0
1
when did they stop making pull tabs on beer cans
 1980s
['1990', '1970s']
1
0
0
when did the book thief movie come out
 2013
['November 27, 2013', '2013', 'November\xa027,\xa02013']
1
0
1
what episode does marnie come back in geordie shore
 Season 14, Episode 5
['5']
1
0
1
when is the strictly come dancing results show recorded
 Sunday
['Saturday', 'Sunday night']
1
0
1
when was the r10+20 summit in rio de janeiro held
 2012
['June 2012', '13 to 22 June 2012']
1
0
1
how long is the famous suspension bridge in san francisco and what is it called
 Golden Gate Bridge
['one-mile-wide', 'Golden Gate Bridge']
1
0
1
last episode of what happens to my family
 “Father’s Love”
['53']
1
0
0
when does body temperature tend to be lowest
 during sleep
['11 p.m. to 3 a.m.']
1
0
1
when does zay come to girl meets world
 Season 3
['May\xa013,\xa02015']
1
0
0
when does the sword art online movie take place
 between the events of the second and third seasons
['2026', 'the year 2026']
1
0
0
when did come fly with me come out
 2010
['25 December 2010']
1
0
1
when are the next commonwealth games going to be held
 Gold Coast, Australia
['2022']
1
0
0
when did the broncos win the super bowl
 1997, 1998, and 2013
['1998', '2015', '1997']
0
1
1

### EMDR

In [109]:
inst_zero=0
inst_few=0
for d in pred:
    if d['insteval']==d['human']:
        inst_zero+=1
    
    if d['insteval_few']==d['human']:
        inst_few+=1
print(inst_zero/len(pred))
print(inst_few/len(pred))

0.924
0.904

### InstGPTeval zero

In [80]:
for d in pred:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.".format(d['question'], answers, d['prediction'])
    response = openai.Completion.create(
                    model='text-davinci-003',
                        prompt=prompt,
                        temperature=0.7,
                        max_tokens=20,
                        top_p=1,
                        frequency_penalty=0.0,
                        presence_penalty=0.0)
    d['insteval']=response['choices'][0]['text']

In [81]:
print(pred[0])

{'question': 'what was the population of the roman empire at its height', 'answer': ['50 to 90\xa0million inhabitants', '70\xa0million', '55–60 million', 'an estimated 70\xa0million people'], 'ans_type': 'CARDINAL', 'prediction': '70 million people', 'human': 1, 'id': 3064, 'bs': 0.8264985084533691, 'bs_th': 1, 'em': False, 'f1': 0.8571428571428571, 'f1_th': 1, 'bem': 1, 'nem_ans': 1, 'nem_sen': 1, 'nem_integ': 1, 'emnem': 1, 'insteval': '\n\n1'}

In [82]:
for d in pred:
    if type(d['insteval'])==int:
        continue
    if 'Answer:' in str(d['insteval']):
        d['insteval']=d['insteval'].replace('Answer:', '')
    d['insteval']=d['insteval'].replace('\n', '')
    d['insteval']=d['insteval'].replace(' ', '')
    d['insteval']=int(d['insteval'])

In [83]:
for d in pred:
    if d['insteval']!=1 and d['insteval']!=0:
        print(d)

In [84]:
inst_hum=0
for d in pred:
    if (d['human'])==d['insteval']:
        inst_hum+=1
    if d['human']!=d['insteval']:
        print(d['question'])
        print(d['prediction'])
        print(d['answer'])
        print(d['ans_type'])
        print(d['human'])
        print(d['insteval'])
        print()  
print(inst_hum/len(pred))

when is the flash coming back after christmas
2018
['January\xa016,\xa02018']
DATE
1
0

what is the share of agriculture in indian economy
15.4%
['17.32%', '23%']
PERCENT
0
1

when do the walking dead comics come out
monthly
['October\xa02003\xa0– present', '2003']
DATE
0
1

how tall is the actor who plays hagrid in harry potter
Robbie Coltrane
['6ft 1in']
QUANTITY
0
1

when did france and belgium invade the ruhr
between 1923 and 1925
['11 January 1923', 'January 1923', '1923']
DATE
1
0

when does the dlc for rainbow six siege come out
post-launch
['January 2018']
DATE
0
1

when does the world cup of hockey start
28 November
['2020']
DATE
0
1

what do mobile numbers start with in the uk
077
['0']
CARDINAL
1
0

when does the next warrior book come out
2018
['April 10, 2018']
DATE
1
0

how many pitchers does a major league team have
five
['five starting pitchers', 'seven relief pitchers']
CARDINAL
1
0

how much is the united states in debt to china
about $1.18 trillion
['$1.06 trillion', '1,200.5']
MONEY
0
1

with a land area of 54 314 square miles where does wisconsin rank among the 50 states
23rd largest
['25']
CARDINAL
0
1

when did the book thief movie come out
November 8, 2013
['November 27, 2013', '2013', 'November\xa027,\xa02013']
DATE
1
0

how much money did it cost to make gta v
approximately $100 million
['137']
CARDINAL
0
1

the initial unification of upper and lower egypt took place during which period
The Pharaonic Period
['3000 BC', 'c. 3000 BC']
CARDINAL
1
0

when did the nba add the three point line
June 1979
['1979–80', '1979–80 season', 'the 1979–80 season']
DATE
1
0

what is the average salary for a us congressman
$169,300 annually
['$174,000']
MONEY
0
1

how old do you have to be to get a gun licence in nz
18
['16 or older']
DATE
1
0

university of michigan school of public health ranking
University of Michigan
['#4']
MONEY
0
1

when does season 3 of the riveras start
2018
['March\xa011,\xa02018']
DATE
1
0

what is the salary of us secretary of state
$210,700
['$205,700', '$205,700 annually']
MONEY
0
1

when does zay come to girl meets world
season three
['May\xa013,\xa02015']
DATE
0
1

what is the current rate of interest on ppf
8
['7.6% Per Annum', '7.6%']
PERCENT
0
1

0.954

In [85]:
with open(prediction_dir, 'w') as f:
    json.dump(pred, f)

### Few_shot

In [52]:
from tqdm import tqdm

In [ ]:
for d in tqdm(pred):
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    if d['ans_type']=='DATE':
        prompt=few_shot_dic[d['ans_type']]+"Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n".format(d['question'], answers, d['prediction'])
        response = openai.Completion.create(
                        model='text-davinci-003',
                            prompt=prompt,
                            temperature=0.7,
                            max_tokens=20,
                            top_p=1,
                            frequency_penalty=0.0,
                            presence_penalty=0.0)
        d['insteval_few']=response['choices'][0]['text']
    else:
        continue

 14%|█▍        | 72/500 [00:15<01:27,  4.91it/s]

In [ ]:
for d in pred:
    if type(d['insteval_few'])==int:
        continue
    if 'Answer:' in str(d['insteval_few']):
        d['insteval_few']=d['insteval_few'].replace('Answer:', '')
    d['insteval_few']=d['insteval_few'].replace('\n', '')
    d['insteval_few']=d['insteval_few'].replace(' ', '')
    d['insteval_few']=int(d['insteval_few'])

In [ ]:
for d in pred:
    if d['insteval_few']!=1 and d['insteval_few']!=0:
        print(d)

In [ ]:
inst_hum=0
for d in pred:
    if (d['human'])==d['insteval_few']:
        inst_hum+=1
    if d['human']!=d['insteval_few']:
        print(d['question'])
        print(d['prediction'])
        print(d['answer'])
        print(d['ans_type'])
        print(d['human'])
        print(d['insteval_few'])
        print()  
print(inst_hum/len(pred))

In [86]:
with open('/home/donaldo9603/workspace/numeric/data/nq/500samples/r2d2/8512_nq_num_500_r2d2_insteval_few_change.json', 'w') as f:
    json.dump(pred, f)

In [88]:
with open('/home/donaldo9603/workspace/numeric/data/nq/500samples/llama2/8508_nq_dev_num_500_llama2_few_insteval_few_change.json') as f:
    check=json.load(f)

In [89]:
inst_hum=0
for d in check:
    if (d['human'])==d['insteval_few']:
        inst_hum+=1
print(inst_hum/len(check))

0.93

### Few shot sampling

In [28]:
train_dir='/home/donaldo9603/workspace/numeric/data/ours/numeric_train.json'

In [29]:
with open(train_dir) as f:
    train=json.load(f)

In [30]:
train[0]

{'question': "when's the last time the eagles went to the playoffs",
 'answer': ['2017'],
 'ans_type': 'DATE',
 'ans_pos': ['2017-01-01',
  '01/01/2017',
  'during 2017',
  'in 2017',
  'Jan 1 2017'],
 'sen_pos': ['The Eagles went to the playoffs last in 2017'],
 'ans_neg': ['2013',
  '2012-01-01',
  '227-2-2',
  '267-6-6',
  '6/6/267',
  '4/4/247',
  '01/01/2033',
  'during 2015',
  'in 2030',
  'jun 1 2017',
  'Jan 4 2047',
  'Jan 1 2004']}

In [31]:
cnt=0
for d in train:
    pos_ans=[]
    negative_sen=[]
    pos_ans.extend(d['answer'])
    pos_ans.extend(d['ans_pos'])
    
    gold_in_sen=False
    
    # Find gold answer presentend in Positive sentence
    for idx, ans in enumerate(pos_ans):
        if ans in d['sen_pos'][0]:
            gold_in_sen=True
            gold_idx=idx
            gold_ans=ans
    
    if gold_in_sen:
        cnt+=1
        # Positive sentence extend
        for ans in (pos_ans):
            if gold_ans!=ans:
                d['sen_pos'].append(d['sen_pos'][0].replace(gold_ans, ans))
        
        # Negative sentence extend
        for ans in d['ans_neg']:
            negative_sen.append(d['sen_pos'][0].replace(gold_ans, ans))

        d['sen_neg']=negative_sen
print(cnt)

2407

In [32]:
date=[d for d in train if d['ans_type']=="DATE"]
card=[d for d in train if d['ans_type']=="CARDINAL"]
time=[d for d in train if d['ans_type']=="TIME"]
quant=[d for d in train if d['ans_type']=="QUANTITY"]
perc=[d for d in train if d['ans_type']=="PERCENT"]
mon=[d for d in train if d['ans_type']=="MONEY"]

In [33]:
import random

In [34]:
date_ans_neg=[d for d in date if 'ans_neg' in d.keys()]
date_sen_neg=[d for d in date if 'sen_neg' in d.keys()]

card_ans_neg=[d for d in card if 'ans_neg' in d.keys()]
card_sen_neg=[d for d in card if 'sen_neg' in d.keys()]

time_ans_neg=[d for d in time if 'ans_neg' in d.keys()]
time_sen_neg=[d for d in time if 'sen_neg' in d.keys()]

quant_ans_neg=[d for d in quant if 'ans_neg' in d.keys()]
quant_sen_neg=[d for d in quant if 'sen_neg' in d.keys()]

perc_ans_neg=[d for d in perc if 'ans_neg' in d.keys()]
perc_sen_neg=[d for d in perc if 'sen_neg' in d.keys()]

mon_ans_neg=[d for d in mon if 'ans_neg' in d.keys()]
mon_sen_neg=[d for d in mon if 'sen_neg' in d.keys()]

In [35]:
random.seed(1001)

In [36]:
date_ans_pos=random.sample(date, 8)
date_sen_pos=random.sample(date, 2)
date_ans_neg=random.sample(date_ans_neg, 4)
date_sen_neg=random.sample(date_sen_neg, 2)

card_ans_pos=random.sample(card, 4)
card_sen_pos=random.sample(card, 4)
card_ans_neg=random.sample(card_ans_neg, 4)
card_sen_neg=random.sample(card_sen_neg, 4)

time_ans_pos=random.sample(time, 6)
time_sen_pos=random.sample(time, 2)
time_ans_neg=random.sample(time_ans_neg, 6)
time_sen_neg=random.sample(time_sen_neg, 2)

quant_ans_pos=random.sample(quant, 4)
quant_sen_pos=random.sample(quant, 4)
quant_ans_neg=random.sample(quant_ans_neg, 4)
quant_sen_neg=random.sample(quant_sen_neg, 4)

perc_ans_pos=random.sample(perc, 4)
perc_sen_pos=random.sample(perc, 4)
perc_ans_neg=random.sample(perc_ans_neg, 4)
perc_sen_neg=random.sample(perc_sen_neg, 4)

mon_ans_pos=random.sample(mon, 4)
mon_sen_pos=random.sample(mon, 4)
mon_ans_neg=random.sample(mon_ans_neg, 4)
mon_sen_neg=random.sample(mon_sen_neg, 4)

In [37]:
date_list=[]
for d in date_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    date_list.append(prompt)

for d in date_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    date_list.append(prompt)

for d in date_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    date_list.append(prompt)

for d in date_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    date_list.append(prompt)

In [38]:
card_list=[]
for d in card_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    card_list.append(prompt)

for d in card_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    card_list.append(prompt)

for d in card_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    card_list.append(prompt)

for d in card_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    card_list.append(prompt)

In [41]:
time_list=[]
for d in time_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    time_list.append(prompt)

for d in time_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    time_list.append(prompt)

for d in time_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    print(d)
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    time_list.append(prompt)

for d in time_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    time_list.append(prompt)

{'question': 'game of thrones season 1 episode 1 running time', 'answer': ['62 minutes'], 'ans_type': 'TIME', 'ans_pos': ['62 min', '1 hr 2 min', '1 hour and 2 minutes', 'one hour and two minutes'], 'sen_pos': ['The running time of Game of Thrones season 1 episode 1 is 62 minutes.', 'The running time of Game of Thrones season 1 episode 1 is 62 minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is 1 hr 2 minutes.', 'The running time of Game of Thrones season 1 episode 1 is 1 hour and 2 minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is one hour and two minutesutes.'], 'ans_neg': ['72 minutes', '64 min', '3 hr 2 min', '1 hr 6 min', '3 hour and 2 minutes', '1 hour and 1 minutes', 'zero hour and two minutes', 'one hour and thirteen minutes'], 'sen_neg': ['The running time of Game of Thrones season 1 episode 1 is 72 minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is 64 minutes.', 'The running time of Game of Thrones season 1 episode 1 is 3 hr 2 minutes.', 'The running time of Game of Thrones season 1 episode 1 is 1 hr 6 minutes.', 'The running time of Game of Thrones season 1 episode 1 is 3 hour and 2 minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is 1 hour and 1 minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is zero hour and two minutesutes.', 'The running time of Game of Thrones season 1 episode 1 is one hour and thirteen minutesutes.']}
{'question': 'When did Edmund Burke graduate?', 'ans_type': 'TIME', 'answer': ['1748'], 'ans_pos': ['1748 AD', 'in the year 1748'], 'sen_pos': ['Edmund Burke graduated in 1748.', 'Edmund Burke graduated in 1748 AD.', 'Edmund Burke graduated in in the year 1748.'], 'ans_neg': ['1758', '1750 AD', 'in the year 1740'], 'sen_neg': ['Edmund Burke graduated in 1758.', 'Edmund Burke graduated in 1750 AD.', 'Edmund Burke graduated in in the year 1740.']}
{'question': 'when did humans first settle in new zealand', 'answer': ['around 1280 CE'], 'ans_type': 'TIME', 'ans_pos': ['12th century CE', 'the 13th century', 'in the late 1200s'], 'sen_pos': ['Humans first settled in New Zealand around 1280 CE.', 'Humans first settled in New Zealand 12th century CE.', 'Humans first settled in New Zealand the 13th century.', 'Humans first settled in New Zealand in the late 1200s.'], 'ans_neg': ['around 1265 CE'], 'sen_neg': ['Humans first settled in New Zealand around 1265 CE.']}
{'question': 'What inconsistency would be found in this explanation?', 'ans_type': 'TIME', 'answer': ['the lunar eclipse would not have been visible during daylight hours'], 'ans_pos': ['A lunar eclipse cannot be seen during the day', 'The explanation suggests that the lunar eclipse occurred during daylight hours', 'The explanation claims that the lunar eclipse was visible during the day', 'This explanation states that a lunar eclipse is visible during the day'], 'sen_pos': ['An inconsistency in this explanation is that the lunar eclipse would not have been visible during daylight hours.', 'An inconsistency in this explanation is that A lunar eclipse cannot be seen during the day.', 'An inconsistency in this explanation is that The explanation suggests that the lunar eclipse occurred during daylight hours.', 'An inconsistency in this explanation is that The explanation claims that the lunar eclipse was visible during the day.', 'An inconsistency in this explanation is that This explanation states that a lunar eclipse is visible during the day.'], 'ans_neg': [], 'sen_neg': []}

IndexError: list index out of range

In [42]:
quant_list=[]
for d in quant_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    quant_list.append(prompt)

for d in quant_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    quant_list.append(prompt)

for d in quant_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    quant_list.append(prompt)

for d in quant_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    quant_list.append(prompt)

In [43]:
perc_list=[]
for d in perc_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    perc_list.append(prompt)

for d in perc_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    perc_list.append(prompt)

for d in perc_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    perc_list.append(prompt)

for d in perc_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    perc_list.append(prompt)

In [44]:
mon_list=[]
for d in mon_ans_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_pos'][0],str(1))
    mon_list.append(prompt)

for d in mon_sen_pos:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_pos'][0],str(1))
    mon_list.append(prompt)

for d in mon_ans_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['ans_neg'][0],str(0))
    mon_list.append(prompt)

for d in mon_sen_neg:
    answers=''
    for ans in d['answer']:
        answers+=ans+', '
    answers=answers[:-2]
    prompt="Question: {}\nAnswer: {}\nCandidate: {}\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n{}\n".format(d['question'], answers, d['sen_neg'][0],str(0))
    mon_list.append(prompt)

In [45]:
few_shot_dic={"DATE":"", "CARDINAL":"", "TIME":"", "QUANTITY":"", "PERCENT":"", "MONEY":""}

In [39]:
for d in random.sample(date,4):
    print(d)

{'question': 'how long was the russian war in afghanistan', 'answer': ['over nine years'], 'ans_type': 'DATE', 'ans_pos': ['1979-1989', '1979 to 1989', 'from 1979 to 1989', 'from 1979 till 1989', 'nine years and few months'], 'sen_pos': ['Russian War in Afghanistan lasted for over nine years - 1979-1989', 'Russian War in Afghanistan lasted for over nine years - over nine years', 'Russian War in Afghanistan lasted for over nine years - 1979 to 1989', 'Russian War in Afghanistan lasted for over nine years - from 1979 to 1989', 'Russian War in Afghanistan lasted for over nine years - from 1979 till 1989', 'Russian War in Afghanistan lasted for over nine years - nine years and few months'], 'ans_neg': ['1992-1989', '1979-1995', '1986 to 1989', '1979 to 1980', 'from 1960 to 1989', 'from 1979 to 1987', 'from 1998 till 1989', 'from 1979 till 1998'], 'sen_neg': ['Russian War in Afghanistan lasted for over nine years - 1992-1989', 'Russian War in Afghanistan lasted for over nine years - 1979-1995', 'Russian War in Afghanistan lasted for over nine years - 1986 to 1989', 'Russian War in Afghanistan lasted for over nine years - 1979 to 1980', 'Russian War in Afghanistan lasted for over nine years - from 1960 to 1989', 'Russian War in Afghanistan lasted for over nine years - from 1979 to 1987', 'Russian War in Afghanistan lasted for over nine years - from 1998 till 1989', 'Russian War in Afghanistan lasted for over nine years - from 1979 till 1998']}
{'question': 'Around what year was the Greek Revival added to the repertory?', 'ans_type': 'DATE', 'answer': ['around 1750'], 'ans_pos': ['in 1750s', 'in the mid-1700s', 'in the 1700s', 'during the mid-18th century', 'during the 18th century'], 'sen_pos': ['Greek Revival was added to the repertory around 1750', 'Greek Revival was added to the repertory in 1750s', 'Greek Revival was added to the repertory in the mid-1700s', 'Greek Revival was added to the repertory in the 1700s', 'Greek Revival was added to the repertory during the mid-18th century', 'Greek Revival was added to the repertory during the 18th century'], 'ans_neg': ['around 1767'], 'sen_neg': ['Greek Revival was added to the repertory around 1767']}
{'question': "Where did she perform wearing Baker's hula skirt?", 'ans_type': 'DATE', 'answer': ['2006 Fashion Rocks concert'], 'ans_pos': ['2006 Fashion Rocks', 'at the 2006 Fashion Rocks concert', 'on the 2006 Fashion Rocks concert', 'in the 2006 Fashion Rocks show', 'at the 2006 Fashion Rocks show'], 'sen_pos': ["She performed wearing Baker's hula skirt at the 2006 Fashion Rocks concert.", "She performed wearing Baker's hula skirt 2006 Fashion Rocks concert.", "She performed wearing Baker's hula skirt 2006 Fashion Rocks.", "She performed wearing Baker's hula skirt on the 2006 Fashion Rocks concert.", "She performed wearing Baker's hula skirt in the 2006 Fashion Rocks show.", "She performed wearing Baker's hula skirt at the 2006 Fashion Rocks show."], 'ans_neg': ['2015 Fashion Rocks concert', '2019 Fashion Rocks', 'at the 2007 Fashion Rocks concert', 'on the 2011 Fashion Rocks concert', 'in the 2011 Fashion Rocks show', 'at the 2023 Fashion Rocks show'], 'sen_neg': ["She performed wearing Baker's hula skirt 2015 Fashion Rocks concert.", "She performed wearing Baker's hula skirt 2019 Fashion Rocks.", "She performed wearing Baker's hula skirt at the 2007 Fashion Rocks concert.", "She performed wearing Baker's hula skirt on the 2011 Fashion Rocks concert.", "She performed wearing Baker's hula skirt in the 2011 Fashion Rocks show.", "She performed wearing Baker's hula skirt at the 2023 Fashion Rocks show."]}
{'question': 'when did seat belts become law in illinois', 'answer': ['January 1, 1988'], 'ans_type': 'DATE', 'ans_pos': ['1988-01-01', '01/01/1988', 'in 1988', 'January 1st, 1988', 'on Jan 1, 1988'], 'sen_pos': ['Seat belts became law in Illinois in January 1, 1988', 'Seat belts became law in Illinois in 1988-01-01', 'Seat belts became law in Illinois in 01/01/1988', 'Seat belts became law in Illinois in in 1988', 'Seat belts became law in Illinois in January 1st, 1988', 'Seat belts became law in Illinois in on Jan 1, 1988'], 'ans_neg': ['june 1, 1988', 'January 1, 1995', '1991-01-01', '1988-4-4', '1988-5-5', '2/2/1988', '2/2/1988', '01/01/2005', 'in 2007', 'february 1st, 1988', 'January 1st, 2003', 'on sep 1, 1988', 'on Jan 1, 1986'], 'sen_neg': ['Seat belts became law in Illinois in june 1, 1988', 'Seat belts became law in Illinois in January 1, 1995', 'Seat belts became law in Illinois in 1991-01-01', 'Seat belts became law in Illinois in 1988-4-4', 'Seat belts became law in Illinois in 1988-5-5', 'Seat belts became law in Illinois in 2/2/1988', 'Seat belts became law in Illinois in 2/2/1988', 'Seat belts became law in Illinois in 01/01/2005', 'Seat belts became law in Illinois in in 2007', 'Seat belts became law in Illinois in february 1st, 1988', 'Seat belts became law in Illinois in January 1st, 2003', 'Seat belts became law in Illinois in on sep 1, 1988', 'Seat belts became law in Illinois in on Jan 1, 1986']}

In [48]:
date_list

['Question: During what era was The Defence Research and Development Organisation founded?\nAnswer: From the 1950s to the 1970s\nCandidate: 1950s-70s\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: In which year was there a cover article on the National Geographic regarding diet recommendations?\nAnswer: 2005\nCandidate: in 2005\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: when did world war 2 become a world war\nAnswer: 1939\nCandidate: 1939-09-01\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: For how long does the fixed rate of tuition last?\nAnswer: 48 months\nCandidate: 4 years\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 "Question: thank god it's friday expression based casual restaurant\nAnswer: TGI Fridays\nCandidate: TGIF\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n",
 'Question: WHen was Black Wednesday?\nAnswer: September 1992\nCandidate: 16/09/1992\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: when was the first film made in colour\nAnswer: 1912\nCandidate: 1912-1913\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: For how long are the other members of the Executive Board appointed?\nAnswer: non-renewable terms of eight years\nCandidate: 8 years\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: What years did the Jewish population rise from 800,000 to two million?\nAnswer: 1948 and 1958\nCandidate: Jewish population rose from 800,000 to two million between 1948 and 1958.\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: when did construction start on the golden gate bridge\nAnswer: January 5, 1933\nCandidate: Construction started on Golden Gate Bridge in January 5, 1933.\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: In what year was Narayanhity constructed?\nAnswer: 1970\nCandidate: 1974\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n0\n',
 'Question: whats the legal age to get a tattoo\nAnswer: 18 years or older\nCandidate: 19 years or older\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n0\n',
 'Question: when did the first super mario come out\nAnswer: September 13, 1985\nCandidate: 1985\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n',
 'Question: In what year did the Battle of Nezib take place?\nAnswer: 1839\nCandidate: 1854\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n0\n',
 'Question: when was the last time tampa bay was hit by a hurricane\nAnswer: 1921\nCandidate: Last time Tampa Bay was hit by a hurricane was 1923\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n0\n',
 'Question: When did Beyond the Mat come out? \nAnswer: 1999\nCandidate: Beyond the Mat come out in 2016\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n0\n']

In [47]:
date_list[-4]='Question: when did the first super mario come out\nAnswer: September 13, 1985\nCandidate: 1985\nPrint 1 if candidate is correct, print 0 if candidate is wrong.\n1\n'

In [49]:
date_few_shot=''
random.shuffle(date_list)
for d in date_list:
    date_few_shot+=d
few_shot_dic['DATE']=date_few_shot

In [152]:
card_few_shot=''
random.shuffle(card_list)
for d in card_list:
    card_few_shot+=d
few_shot_dic['CARDINAL']=card_few_shot

In [153]:
quant_few_shot=''
random.shuffle(quant_list)
for d in quant_list:
    quant_few_shot+=d
few_shot_dic['QUANTITY']=quant_few_shot

In [154]:
perc_few_shot=''
random.shuffle(perc_list)
for d in perc_list:
    perc_few_shot+=d
few_shot_dic['PERCENT']=perc_few_shot

In [155]:
time_few_shot=''
random.shuffle(time_list)
for d in time_list:
    time_few_shot+=d
few_shot_dic['TIME']=time_few_shot

In [156]:
mon_few_shot=''
random.shuffle(mon_list)
for d in mon_list:
    mon_few_shot+=d
few_shot_dic['MONEY']=mon_few_shot

In [157]:
print(few_shot_dic['DATE'])

Question: For how long does the fixed rate of tuition last?
Answer: 48 months
Candidate: Fixed rate of tuition lasts for 48 months or 4 years.
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: when was sergeant pepper released in the us
Answer: 2 June 1967
Candidate: Sergeant Pepper was released in the US on 4 June 1967
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: WHen was Black Wednesday?
Answer: September 1992
Candidate: Black Wednesday was in September 1992
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: when does the i phone 7 come out
Answer: September 16, 2016
Candidate: iPhone 7 was released in december 16, 2016
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: For how long does the fixed rate of tuition last?
Answer: 48 months
Candidate: 4 years
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: When did youtube launch the version of "shows" for the UK?
Answer: In November 2009
Candidate: Youtube launched the version of "shows" for the UK in In february 2009
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: In which year was there a cover article on the National Geographic regarding diet recommendations?
Answer: 2005
Candidate: in 2005
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: when did world war 2 become a world war
Answer: 1939
Candidate: 1939-09-01
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: when did construction start on the golden gate bridge
Answer: January 5, 1933
Candidate: october 5, 1933
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: In what year was Narayanhity constructed?
Answer: 1970
Candidate: 1974
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: During what era was The Defence Research and Development Organisation founded?
Answer: From the 1950s to the 1970s
Candidate: 1950s-70s
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: when was the last time tampa bay was hit by a hurricane
Answer: 1921
Candidate: Last time Tampa Bay was hit by a hurricane was 1923
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: thank god it's friday expression based casual restaurant
Answer: TGI Fridays
Candidate: Thank God It's Friday expression based casual restaurant is TGI Fridays
Print 1 if candidate is correct, print 0 if candidate is wrong.
1
Question: What years did the Jewish population rise from 800,000 to two million?
Answer: 1948 and 1958
Candidate: 1929 and 1958
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: For how long are the other members of the Executive Board appointed?
Answer: non-renewable terms of eight years
Candidate: 9 years
Print 1 if candidate is correct, print 0 if candidate is wrong.
0
Question: when was the first film made in colour
Answer: 1912
Candidate: The first film made in colour was in 1912
Print 1 if candidate is correct, print 0 if candidate is wrong.
1